---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lujiewen.
--- DateTime: 2018/12/24 上午11:24
---
---
local cjson = require('cjson')
local http = require "resty.http"

local httpc = http.new()

local url = ngx.var.scheme .. '://' .. ngx.var.server_name .. ':' .. ngx.var.server_port .. "/validate"
local res, err = httpc:request_uri(url, {
    method = "GET",
    headers = { ["Cookie"] = ngx.var.http_cookie, },
    --keepalive_timeout = 60,
    --keepalive_pool = 10
})

if not res then
    ngx.say("failed to request: ", err)
    return
end

if not res.status == 200 then
    ngx.say("status failed: ", res.status)
    return
end

local body = cjson.decode(res.body)
if not body.status then
    require('redirect_block')()
    return
end