---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lujiewen.
--- DateTime: 2018/12/24 上午11:24
---
---
local cjson = require('cjson')

local res = ngx.location.capture('/validate')

if not res then
    return ngx.say("failed to request: ", err)
end

if not res.status == 200 then
    return ngx.say("status failed: ", res.status)
end

local body = cjson.decode(res.body)
if not body.status then
    if 'XMLHttpRequest' == ngx.req.get_headers()['X-Requested-With'] then
        --如果是ajax请求响应
        return ngx.exit(ngx.HTTP_UNAUTHORIZED)
    else
        local source = ngx.var.scheme .. '://' .. ngx.var.server_name .. ':' .. ngx.var.server_port .. ngx.var.request_uri
        local redirect_uri = '/login?redirect_uri=' .. ngx.escape_uri(source)
        return ngx.redirect(redirect_uri, ngx.HTTP_MOVED_TEMPORARILY)
    end
end