---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lujiewen.
--- DateTime: 2018/12/23 上午11:40
---
local redis = require('resty.redis')
local cjson = require('cjson')

count = 1

local share_data = ngx.shared.shared_data
share_data:set('count',1)