---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lujiewen.
--- DateTime: 2019/1/12 下午4:23
---
if not string.find(ngx.var.request_uri, '.', 1, true) then
    return ngx.redirect('/test/pc/index.html')
end