---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lujiewen.
--- DateTime: 2018/12/23 下午1:54
---

local uri_args = ngx.req.get_uri_args()

local i = uri_args['i'] or 0
local j = uri_args['j'] or 0

return i + j