server:
  port: 8401
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cadb_v50?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: com.mvwchina.funcation.basicauth.CustomPhysicalNamingStrategy
  devtools:
    restart:
      enabled: true
      exclude: static/**,public/**
  redis:
    host: 127.0.0.1
    port: 6379
    password:
#    database: 0
