spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/uums
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      validation-query: select 1
      test-while-idle: true
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  devtools:
    restart:
      exclude: static/**,public/**

#spring.datasource.url=jdbc:mariadb://developer.mvwchina.com:3306/uums
#spring.datasource.username=mdb
#spring.datasource.password=123456

# hibernate.X
#spring.jpa.show-sql=true
#spring.jpa.open-in-view=false
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.datasource.tomcat.validation-query=select 1
#spring.datasource.tomcat.test-while-idle=true
#spring.datasource.data=import_entities.sql
#spring.devtools.restart.exclude=